"""empty message

Revision ID: 1c8fd5cd6a40
Revises: 424375ae604d
Create Date: 2015-11-14 00:11:57.387610

"""

# revision identifiers, used by Alembic.
revision = '1c8fd5cd6a40'
down_revision = '424375ae604d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'deleted')
    ### end Alembic commands ###
