"""empty message

Revision ID: 1edb244c2143
Revises: dda8b5e16e1
Create Date: 2015-11-14 18:25:12.326467

"""

# revision identifiers, used by Alembic.
revision = '1edb244c2143'
down_revision = 'dda8b5e16e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
