"""empty message

Revision ID: 1ffcdec21e62
Revises: 46abdcb34191
Create Date: 2016-01-16 22:51:54.959669

"""

# revision identifiers, used by Alembic.
revision = '1ffcdec21e62'
down_revision = '46abdcb34191'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('alt_text', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'alt_text')
    ### end Alembic commands ###
