"""empty message

Revision ID: 219cec066439
Revises: 29a7309cf37f
Create Date: 2016-01-12 23:01:45.822381

"""

# revision identifiers, used by Alembic.
revision = '219cec066439'
down_revision = '29a7309cf37f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paragraph', sa.Column('abstract', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paragraph', 'abstract')
    ### end Alembic commands ###
