"""empty message

Revision ID: 26c69113cbf6
Revises: 5219094968f4
Create Date: 2016-01-12 14:22:56.178367

"""

# revision identifiers, used by Alembic.
revision = '26c69113cbf6'
down_revision = '5219094968f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'deleted')
    ### end Alembic commands ###
