"""empty message

Revision ID: 294c1d418a40
Revises: 43a666ac5370
Create Date: 2016-01-09 17:27:43.958286

"""

# revision identifiers, used by Alembic.
revision = '294c1d418a40'
down_revision = '43a666ac5370'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text('ALTER TABLE page MODIFY COLUMN layout varchar(255)'))
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
