"""empty message

Revision ID: 29a7309cf37f
Revises: 26c69113cbf6
Create Date: 2016-01-12 20:56:16.089265

"""

# revision identifiers, used by Alembic.
revision = '29a7309cf37f'
down_revision = '26c69113cbf6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('gallery_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'gallery_id')
    ### end Alembic commands ###
