"""empty message

Revision ID: 327b91ae10af
Revises: 56ae6bead8f7
Create Date: 2015-11-15 08:45:24.023180

"""

# revision identifiers, used by Alembic.
revision = '327b91ae10af'
down_revision = '56ae6bead8f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('image', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'deleted')
    op.drop_column('image', 'created')
    ### end Alembic commands ###
