"""empty message

Revision ID: 338fdbe4e699
Revises: 28f617f87e31
Create Date: 2014-08-26 06:45:05.761199

"""

# revision identifiers, used by Alembic.
revision = '338fdbe4e699'
down_revision = '28f617f87e31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
