"""empty message

Revision ID: 354bd1d391c3
Revises: 40767b19e15e
Create Date: 2015-11-14 06:32:56.545480

"""

# revision identifiers, used by Alembic.
revision = '354bd1d391c3'
down_revision = '40767b19e15e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('section_type', sa.Enum('content', 'blog'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'section_type')
    ### end Alembic commands ###
