"""empty message

Revision ID: 38a899e7b6f2
Revises: 3565b16d313e
Create Date: 2016-01-09 12:03:19.347263

"""

# revision identifiers, used by Alembic.
revision = '38a899e7b6f2'
down_revision = '3565b16d313e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'time')
    ### end Alembic commands ###
