"""empty message

Revision ID: 38c12e0291f6
Revises: 1ffcdec21e62
Create Date: 2016-01-17 18:40:25.664933

"""

# revision identifiers, used by Alembic.
revision = '38c12e0291f6'
down_revision = '1ffcdec21e62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_component', sa.Column('fourth_href', sa.String(length=512), nullable=True))
    op.add_column('page_component', sa.Column('fourth_title', sa.Text(), nullable=True))
    op.add_column('page_component', sa.Column('second_href', sa.String(length=512), nullable=True))
    op.add_column('page_component', sa.Column('second_title', sa.Text(), nullable=True))
    op.add_column('page_component', sa.Column('third_href', sa.String(length=512), nullable=True))
    op.add_column('page_component', sa.Column('third_title', sa.Text(), nullable=True))
    op.add_column('page_component', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_component', 'title')
    op.drop_column('page_component', 'third_title')
    op.drop_column('page_component', 'third_href')
    op.drop_column('page_component', 'second_title')
    op.drop_column('page_component', 'second_href')
    op.drop_column('page_component', 'fourth_title')
    op.drop_column('page_component', 'fourth_href')
    ### end Alembic commands ###
