"""empty message

Revision ID: 394a8512df4d
Revises: ba9983a2313
Create Date: 2015-11-14 11:13:37.518521

"""

# revision identifiers, used by Alembic.
revision = '394a8512df4d'
down_revision = 'ba9983a2313'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('paragraph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('layout', sa.Enum('content'), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tags_paragraphs',
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('tags_pages',
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('pages_paragraphs',
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.id'], )
    )
    op.add_column(u'page', sa.Column('fundraiser_end_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'page', 'fundraiser_end_time')
    op.drop_table('pages_paragraphs')
    op.drop_table('tags_pages')
    op.drop_table('tags_paragraphs')
    op.drop_table('paragraph')
    op.drop_table('tag')
    ### end Alembic commands ###
