"""empty message

Revision ID: 424375ae604d
Revises: 38466ac0c86a
Create Date: 2015-11-14 00:06:09.213031

"""

# revision identifiers, used by Alembic.
revision = '424375ae604d'
down_revision = '38466ac0c86a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
