"""empty message

Revision ID: 43a666ac5370
Revises: 38a899e7b6f2
Create Date: 2016-01-09 17:23:23.953118

"""

# revision identifiers, used by Alembic.
revision = '43a666ac5370'
down_revision = '38a899e7b6f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
