"""empty message

Revision ID: 446c9643a612
Revises: 338fdbe4e699
Create Date: 2014-08-26 08:18:21.147546

"""

# revision identifiers, used by Alembic.
revision = '446c9643a612'
down_revision = '338fdbe4e699'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    ### end Alembic commands ###
