"""empty message

Revision ID: 46abdcb34191
Revises: 4d1b3e296421
Create Date: 2016-01-16 22:22:08.044862

"""

# revision identifiers, used by Alembic.
revision = '46abdcb34191'
down_revision = '4d1b3e296421'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_component', sa.Column('fourth_text', sa.Text(), nullable=True))
    op.add_column('page_component', sa.Column('second_text', sa.Text(), nullable=True))
    op.add_column('page_component', sa.Column('third_text', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_component', 'third_text')
    op.drop_column('page_component', 'second_text')
    op.drop_column('page_component', 'fourth_text')
    ### end Alembic commands ###
