"""empty message

Revision ID: 4d1b3e296421
Revises: 219cec066439
Create Date: 2016-01-13 00:02:19.425524

"""

# revision identifiers, used by Alembic.
revision = '4d1b3e296421'
down_revision = '219cec066439'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_component', sa.Column('link_to_section_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_component', 'link_to_section_id')
    ### end Alembic commands ###
