"""empty message

Revision ID: 4e4e9624d8e7
Revises: 81585f5ae07
Create Date: 2016-01-08 00:03:04.967302

"""

# revision identifiers, used by Alembic.
revision = '4e4e9624d8e7'
down_revision = '81585f5ae07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('current_progress', sa.Integer(), nullable=True))
    op.add_column('participant', sa.Column('donation_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'donation_count')
    op.drop_column('participant', 'current_progress')
    ### end Alembic commands ###
