"""empty message

Revision ID: 5219094968f4
Revises: 731653c2515
Create Date: 2016-01-12 00:30:29.942533

"""

# revision identifiers, used by Alembic.
revision = '5219094968f4'
down_revision = '731653c2515'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
