"""empty message

Revision ID: 559565b45d06
Revises: 4e4e9624d8e7
Create Date: 2016-01-08 22:27:57.816117

"""

# revision identifiers, used by Alembic.
revision = '559565b45d06'
down_revision = '4e4e9624d8e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paragraph', sa.Column('photos', sa.Integer(), nullable=True))
    op.add_column('paragraph', sa.Column('time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paragraph', 'time')
    op.drop_column('paragraph', 'photos')
    ### end Alembic commands ###
