"""empty message

Revision ID: 58fcf04c1c22
Revises: None
Create Date: 2014-08-26 06:10:26.406944

"""

# revision identifiers, used by Alembic.
revision = '58fcf04c1c22'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
