"""empty message

Revision ID: 731653c2515
Revises: f6e59558984
Create Date: 2016-01-11 22:22:42.129984

"""

# revision identifiers, used by Alembic.
revision = '731653c2515'
down_revision = 'f6e59558984'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('dynamic_page_data', sa.Integer(), nullable=True))
    op.drop_column('page', 'landing_page_data')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('landing_page_data', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('page', 'dynamic_page_data')
    ### end Alembic commands ###
