"""empty message

Revision ID: 81585f5ae07
Revises: 327b91ae10af
Create Date: 2016-01-08 00:00:05.285106

"""

# revision identifiers, used by Alembic.
revision = '81585f5ae07'
down_revision = '327b91ae10af'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'gallery_id')
    op.drop_column('participant', 'gallery')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('gallery', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('participant', sa.Column('gallery_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
