"""empty message

Revision ID: 8935112e3f
Revises: 1edb244c2143
Create Date: 2015-11-14 18:26:40.355042

"""

# revision identifiers, used by Alembic.
revision = '8935112e3f'
down_revision = '1edb244c2143'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
