"""empty message

Revision ID: ba9983a2313
Revises: 3d9f44ed82b5
Create Date: 2015-11-14 06:39:56.192419

"""

# revision identifiers, used by Alembic.
revision = 'ba9983a2313'
down_revision = '3d9f44ed82b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
