"""empty message

Revision ID: dda8b5e16e1
Revises: 394a8512df4d
Create Date: 2015-11-14 17:35:44.598444

"""

# revision identifiers, used by Alembic.
revision = 'dda8b5e16e1'
down_revision = '394a8512df4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=511), nullable=True),
    sa.Column('photos', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('goal', sa.Integer(), nullable=True),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['page.id'], ),
    sa.ForeignKeyConstraint(['photos'], ['gallery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    ### end Alembic commands ###
