"""empty message

Revision ID: e82d441bcc4
Revises: 8935112e3f
Create Date: 2015-11-14 18:29:22.331645

"""

# revision identifiers, used by Alembic.
revision = 'e82d441bcc4'
down_revision = '8935112e3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
